title: Hacker theme
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
title: Nisarg Dave Portfolio
description: A portfolio website to showcase my writeups and achievements
